Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
forest = RandomForestClassifier(
    n_estimators=5, bootstrap=True, random_state=3, max_depth=3, max_features="auto"
)

forest.fit(X, y)

print("R-Squared Score:", forest.score(Xtest, ytrueTest))
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mInvalidParameterError[0m                     Traceback (most recent call last)
Cell [0;32mIn[23], line 5[0m
[1;32m      1[0m forest [38;5;241m=[39m RandomForestClassifier(
[1;32m      2[0m     n_estimators[38;5;241m=[39m[38;5;241m5[39m, bootstrap[38;5;241m=[39m[38;5;28;01mTrue[39;00m, random_state[38;5;241m=[39m[38;5;241m3[39m, max_depth[38;5;241m=[39m[38;5;241m3[39m, max_features[38;5;241m=[39m[38;5;124m"[39m[38;5;124mauto[39m[38;5;124m"[39m
[1;32m      3[0m )
[0;32m----> 5[0m [43mforest[49m[38;5;241;43m.[39;49m[43mfit[49m[43m([49m[43mX[49m[43m,[49m[43m [49m[43my[49m[43m)[49m
[1;32m      7[0m [38;5;28mprint[39m([38;5;124m"[39m[38;5;124mR-Squared Score:[39m[38;5;124m"[39m, forest[38;5;241m.[39mscore(Xtest, ytrueTest))

File [0;32m/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/sklearn/base.py:1145[0m, in [0;36m_fit_context.<locals>.decorator.<locals>.wrapper[0;34m(estimator, *args, **kwargs)[0m
[1;32m   1140[0m partial_fit_and_fitted [38;5;241m=[39m (
[1;32m   1141[0m     fit_method[38;5;241m.[39m[38;5;18m__name__[39m [38;5;241m==[39m [38;5;124m"[39m[38;5;124mpartial_fit[39m[38;5;124m"[39m [38;5;129;01mand[39;00m _is_fitted(estimator)
[1;32m   1142[0m )
[1;32m   1144[0m [38;5;28;01mif[39;00m [38;5;129;01mnot[39;00m global_skip_validation [38;5;129;01mand[39;00m [38;5;129;01mnot[39;00m partial_fit_and_fitted:
[0;32m-> 1145[0m     [43mestimator[49m[38;5;241;43m.[39;49m[43m_validate_params[49m[43m([49m[43m)[49m
[1;32m   1147[0m [38;5;28;01mwith[39;00m config_context(
[1;32m   1148[0m     skip_parameter_validation[38;5;241m=[39m(
[1;32m   1149[0m         prefer_skip_nested_validation [38;5;129;01mor[39;00m global_skip_validation
[1;32m   1150[0m     )
[1;32m   1151[0m ):
[1;32m   1152[0m     [38;5;28;01mreturn[39;00m fit_method(estimator, [38;5;241m*[39margs, [38;5;241m*[39m[38;5;241m*[39mkwargs)

File [0;32m/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/sklearn/base.py:638[0m, in [0;36mBaseEstimator._validate_params[0;34m(self)[0m
[1;32m    630[0m [38;5;28;01mdef[39;00m [38;5;21m_validate_params[39m([38;5;28mself[39m):
[1;32m    631[0m [38;5;250m    [39m[38;5;124;03m"""Validate types and values of constructor parameters[39;00m
[1;32m    632[0m 
[1;32m    633[0m [38;5;124;03m    The expected type and values must be defined in the `_parameter_constraints`[39;00m
[0;32m   (...)[0m
[1;32m    636[0m [38;5;124;03m    accepted constraints.[39;00m
[1;32m    637[0m [38;5;124;03m    """[39;00m
[0;32m--> 638[0m     [43mvalidate_parameter_constraints[49m[43m([49m
[1;32m    639[0m [43m        [49m[38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_parameter_constraints[49m[43m,[49m
[1;32m    640[0m [43m        [49m[38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mget_params[49m[43m([49m[43mdeep[49m[38;5;241;43m=[39;49m[38;5;28;43;01mFalse[39;49;00m[43m)[49m[43m,[49m
[1;32m    641[0m [43m        [49m[43mcaller_name[49m[38;5;241;43m=[39;49m[38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[38;5;18;43m__class__[39;49m[38;5;241;43m.[39;49m[38;5;18;43m__name__[39;49m[43m,[49m
[1;32m    642[0m [43m    [49m[43m)[49m

File [0;32m/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/sklearn/utils/_param_validation.py:96[0m, in [0;36mvalidate_parameter_constraints[0;34m(parameter_constraints, params, caller_name)[0m
[1;32m     90[0m [38;5;28;01melse[39;00m:
[1;32m     91[0m     constraints_str [38;5;241m=[39m (
[1;32m     92[0m         [38;5;124mf[39m[38;5;124m"[39m[38;5;132;01m{[39;00m[38;5;124m'[39m[38;5;124m, [39m[38;5;124m'[39m[38;5;241m.[39mjoin([[38;5;28mstr[39m(c)[38;5;250m [39m[38;5;28;01mfor[39;00m[38;5;250m [39mc[38;5;250m [39m[38;5;129;01min[39;00m[38;5;250m [39mconstraints[:[38;5;241m-[39m[38;5;241m1[39m]])[38;5;132;01m}[39;00m[38;5;124m or[39m[38;5;124m"[39m
[1;32m     93[0m         [38;5;124mf[39m[38;5;124m"[39m[38;5;124m [39m[38;5;132;01m{[39;00mconstraints[[38;5;241m-[39m[38;5;241m1[39m][38;5;132;01m}[39;00m[38;5;124m"[39m
[1;32m     94[0m     )
[0;32m---> 96[0m [38;5;28;01mraise[39;00m InvalidParameterError(
[1;32m     97[0m     [38;5;124mf[39m[38;5;124m"[39m[38;5;124mThe [39m[38;5;132;01m{[39;00mparam_name[38;5;132;01m!r}[39;00m[38;5;124m parameter of [39m[38;5;132;01m{[39;00mcaller_name[38;5;132;01m}[39;00m[38;5;124m must be[39m[38;5;124m"[39m
[1;32m     98[0m     [38;5;124mf[39m[38;5;124m"[39m[38;5;124m [39m[38;5;132;01m{[39;00mconstraints_str[38;5;132;01m}[39;00m[38;5;124m. Got [39m[38;5;132;01m{[39;00mparam_val[38;5;132;01m!r}[39;00m[38;5;124m instead.[39m[38;5;124m"[39m
[1;32m     99[0m )

[0;31mInvalidParameterError[0m: The 'max_features' parameter of RandomForestClassifier must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'log2', 'sqrt'} or None. Got 'auto' instead.
InvalidParameterError: The 'max_features' parameter of RandomForestClassifier must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'log2', 'sqrt'} or None. Got 'auto' instead.

